# These are supported funding model platforms
github: Utkarsh56016  # GitHub username
# Uncomment and update these with your actual usernames if you have these accounts
# patreon: your-patreon-username
# open_collective: your-oc-username
# ko_fi: your-kofi-username
# tidelift: your-tidelift-username
# community_bridge: your-cb-username
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# ow2: your-ow2-username
# custom: ['https://your-custom-donation-link.com']
